development:
  adapter: postgresql
  encoding: unicode
  database: social_one_development
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: social_one_production
  pool: 5
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: social_one_test
  pool: 5
  username: root
  password: root